stages:
  - test

variables:
  DOCKER_HOST: tcp://docker:2376

test:api:
  stage: test
  image: maven:3.9-eclipse-temurin-25
  services:
    - docker:dind
  script:
    - docker compose up mock-app --wait -d
    - mvn test -Dgroups=api -DbaseUri=http://mock-app:3000/ -DapiKey=demo-api-key

test:browser:
  stage: test
  image: maven:3.9-eclipse-temurin-25
  services:
    - docker:dind
  script:
    - docker compose up --wait -d
    - mvn test -Dgroups=browser
            -DbaseUri=http://mock-app:3000/
            -DapiKey=demo-api-key
            -DexecutionAddress=http://docker:4444
